// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 5
		case r == 40: // ['(','(']
			return 6
		case r == 41: // [')',')']
			return 7
		case r == 42: // ['*','*']
			return 8
		case r == 43: // ['+','+']
			return 9
		case r == 44: // [',',',']
			return 10
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 12
		case r == 47: // ['/','/']
			return 13
		case r == 48: // ['0','0']
			return 14
		case 49 <= r && r <= 57: // ['1','9']
			return 15
		case r == 58: // [':',':']
			return 16
		case r == 59: // [';',';']
			return 17
		case r == 60: // ['<','<']
			return 18
		case r == 61: // ['=','=']
			return 19
		case r == 62: // ['>','>']
			return 20
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 91: // ['[','[']
			return 22
		case r == 93: // [']',']']
			return 23
		case r == 94: // ['^','^']
			return 24
		case r == 95: // ['_','_']
			return 25
		case r == 96: // ['`','`']
			return 26
		case 97 <= r && r <= 100: // ['a','d']
			return 21
		case r == 101: // ['e','e']
			return 27
		case r == 102: // ['f','f']
			return 28
		case 103 <= r && r <= 104: // ['g','h']
			return 21
		case r == 105: // ['i','i']
			return 29
		case 106 <= r && r <= 109: // ['j','m']
			return 21
		case r == 110: // ['n','n']
			return 30
		case 111 <= r && r <= 113: // ['o','q']
			return 21
		case r == 114: // ['r','r']
			return 31
		case r == 115: // ['s','s']
			return 21
		case r == 116: // ['t','t']
			return 32
		case 117 <= r && r <= 122: // ['u','z']
			return 21
		case r == 123: // ['{','{']
			return 33
		case r == 124: // ['|','|']
			return 34
		case r == 125: // ['}','}']
			return 35
		case r == 126: // ['~','~']
			return 36
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 37
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 38
		case r == 92: // ['\','\']
			return 39
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 40
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 42
		case r == 47: // ['/','/']
			return 43
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 55: // ['0','7']
			return 45
		case 56 <= r && r <= 57: // ['8','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 88: // ['X','X']
			return 48
		case r == 101: // ['e','e']
			return 47
		case r == 120: // ['x','x']
			return 48
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 60: // ['<','<']
			return 49
		case r == 61: // ['=','=']
			return 50
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 51
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 52
		case r == 62: // ['>','>']
			return 53
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 96: // ['`','`']
			return 55
		default:
			return 26
		}
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 107: // ['a','k']
			return 21
		case r == 108: // ['l','l']
			return 56
		case 109 <= r && r <= 122: // ['m','z']
			return 21
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case r == 97: // ['a','a']
			return 57
		case 98 <= r && r <= 109: // ['b','m']
			return 21
		case r == 110: // ['n','n']
			return 58
		case r == 111: // ['o','o']
			return 59
		case 112 <= r && r <= 122: // ['p','z']
			return 21
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 101: // ['a','e']
			return 21
		case r == 102: // ['f','f']
			return 60
		case 103 <= r && r <= 122: // ['g','z']
			return 21
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 116: // ['a','t']
			return 21
		case r == 117: // ['u','u']
			return 61
		case 118 <= r && r <= 122: // ['v','z']
			return 21
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 100: // ['a','d']
			return 21
		case r == 101: // ['e','e']
			return 62
		case 102 <= r && r <= 122: // ['f','z']
			return 21
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 113: // ['a','q']
			return 21
		case r == 114: // ['r','r']
			return 63
		case 115 <= r && r <= 122: // ['s','z']
			return 21
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 124: // ['|','|']
			return 64
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 3
		case r == 110: // ['n','n']
			return 65
		case r == 114: // ['r','r']
			return 65
		case r == 116: // ['t','t']
			return 65
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 41
		case r == 69: // ['E','E']
			return 66
		case r == 101: // ['e','e']
			return 66
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 67
		default:
			return 42
		}
	},
	// S43
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 68
		default:
			return 43
		}
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case r == 69: // ['E','E']
			return 70
		case r == 101: // ['e','e']
			return 70
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 55: // ['0','7']
			return 45
		case 56 <= r && r <= 57: // ['8','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		case r == 69: // ['E','E']
			return 47
		case r == 101: // ['e','e']
			return 47
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 71
		case r == 45: // ['-','-']
			return 71
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 114: // ['a','r']
			return 21
		case r == 115: // ['s','s']
			return 75
		case 116 <= r && r <= 122: // ['t','z']
			return 21
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 107: // ['a','k']
			return 21
		case r == 108: // ['l','l']
			return 76
		case 109 <= r && r <= 122: // ['m','z']
			return 21
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 113: // ['a','q']
			return 21
		case r == 114: // ['r','r']
			return 77
		case 115 <= r && r <= 122: // ['s','z']
			return 21
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 107: // ['a','k']
			return 21
		case r == 108: // ['l','l']
			return 78
		case 109 <= r && r <= 122: // ['m','z']
			return 21
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 115: // ['a','s']
			return 21
		case r == 116: // ['t','t']
			return 79
		case 117 <= r && r <= 122: // ['u','z']
			return 21
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 116: // ['a','t']
			return 21
		case r == 117: // ['u','u']
			return 80
		case 118 <= r && r <= 122: // ['v','z']
			return 21
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 38
		case r == 92: // ['\','\']
			return 39
		default:
			return 3
		}
	},
	// S66
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 81
		case r == 45: // ['-','-']
			return 81
		case 48 <= r && r <= 57: // ['0','9']
			return 82
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 67
		case r == 47: // ['/','/']
			return 83
		default:
			return 42
		}
	},
	// S68
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case r == 69: // ['E','E']
			return 70
		case r == 101: // ['e','e']
			return 70
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 84
		case r == 45: // ['-','-']
			return 84
		case 48 <= r && r <= 57: // ['0','9']
			return 85
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 100: // ['a','d']
			return 21
		case r == 101: // ['e','e']
			return 86
		case 102 <= r && r <= 122: // ['f','z']
			return 21
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 114: // ['a','r']
			return 21
		case r == 115: // ['s','s']
			return 87
		case 116 <= r && r <= 122: // ['t','z']
			return 21
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 107: // ['a','k']
			return 21
		case r == 108: // ['l','l']
			return 88
		case 109 <= r && r <= 122: // ['m','z']
			return 21
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 116: // ['a','t']
			return 21
		case r == 117: // ['u','u']
			return 89
		case 118 <= r && r <= 122: // ['v','z']
			return 21
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 100: // ['a','d']
			return 21
		case r == 101: // ['e','e']
			return 90
		case 102 <= r && r <= 122: // ['f','z']
			return 21
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 82
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 82
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 85
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 85
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 100: // ['a','d']
			return 21
		case r == 101: // ['e','e']
			return 90
		case 102 <= r && r <= 122: // ['f','z']
			return 21
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 113: // ['a','q']
			return 21
		case r == 114: // ['r','r']
			return 91
		case 115 <= r && r <= 122: // ['s','z']
			return 21
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 109: // ['a','m']
			return 21
		case r == 110: // ['n','n']
			return 92
		case 111 <= r && r <= 122: // ['o','z']
			return 21
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 90: // ['A','Z']
			return 21
		case r == 95: // ['_','_']
			return 25
		case 97 <= r && r <= 122: // ['a','z']
			return 21
		}
		return NoState
	},
}
